/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/setup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/activities` | `/activities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}/ledger` | `/ledger`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}/members` | `/members`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}/reports` | `/reports`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/setup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/activities` | `/activities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(staff)'}/attendance` | `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(staff)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(staff)'}/ledger` | `/ledger`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(staff)'}/members` | `/members`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(staff)'}/reports` | `/reports`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/setup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/activities${`?${string}` | `#${string}` | ''}` | `/activities${`?${string}` | `#${string}` | ''}` | `${'/(client)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(staff)'}/attendance${`?${string}` | `#${string}` | ''}` | `/attendance${`?${string}` | `#${string}` | ''}` | `${'/(staff)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(staff)'}/ledger${`?${string}` | `#${string}` | ''}` | `/ledger${`?${string}` | `#${string}` | ''}` | `${'/(staff)'}/members${`?${string}` | `#${string}` | ''}` | `/members${`?${string}` | `#${string}` | ''}` | `${'/(staff)'}/reports${`?${string}` | `#${string}` | ''}` | `/reports${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/setup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/activities` | `/activities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}/ledger` | `/ledger`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}/members` | `/members`; params?: Router.UnknownInputParams; } | { pathname: `${'/(staff)'}/reports` | `/reports`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
